### Menggunakan sjoin() dalam GeoPandas

In [2]:
import geopandas as gpd

# Membaca dua GeoDataFrame
countries = gpd.read_file("./data/ne_110m_admin_0_countries/")
populated_places = gpd.read_file("./data/ne_110m_populated_places/")

# Pastikan kedua GeoDataFrame memiliki CRS (Coordinate Reference System) yang sama
# Jika CRS berbeda, lakukan reproject ke CRS yang sama
if countries.crs != populated_places.crs:
    populated_places = populated_places.to_crs(countries.crs)

# Melakukan spatial join dengan metode 'within' (apakah tempat populasi berada dalam batas negara)
# Mengganti 'op' dengan 'predicate' sesuai versi terbaru GeoPandas
result = gpd.sjoin(populated_places, countries, how="inner", predicate="within")

# Menampilkan beberapa baris hasil spatial join
result.head()

,SCALERANK,NATSCALE,LABELRANK_left,FEATURECLA,NAME_left,NAMEPAR,NAMEALT,NAMEASCII,ADM0CAP,CAPIN,...,FCLASS_VN_right,FCLASS_TR_right,FCLASS_ID_right,FCLASS_PL_right,FCLASS_GR_right,FCLASS_IT_right,FCLASS_NL_right,FCLASS_SE_right,FCLASS_BD_right,FCLASS_UA_right
0,8,10,3,Admin-0 capital,Vatican City,None,None,Vatican City,1,None,...,None,None,None,None,None,None,None,None,None,None
1,7,20,0,Admin-0 capital,San Marino,None,None,San Marino,1,None,...,None,None,None,None,None,None,None,None,None,None
2,7,20,0,Admin-0 capital,Vaduz,None,None,Vaduz,1,None,...,None,None,None,None,None,None,None,None,None,None
3,6,30,8,Admin-0 capital alt,Lobamba,None,None,Lobamba,0,Legislative and,...,None,None,None,None,None,None,None,None,None,None
4,6,30,8,Admin-0 capital,Luxembourg,None,None,Luxembourg,1,None,...,None,None,None,None,None,None,None,None,None,None